let CustomErrorHandler,User;_f01‍.x([["default",()=>_f01‍.o]]);_f01‍.w("../../services.js",[["CustomErrorHandler",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);_f01‍.w("../../models",[["User",["User"],function(v){User=v}]]);


const userController = {
  async me(req, res, next) {
    const _id = req.user._id;
    try {
      const user = await User.find({ _id }).select("-password -updatedAt -__v");

      if (!user) {
        return next(CustomErrorHandler.notFound);
      }

      res.json(user);
    } catch (err) {
      return next(err);
    }
  },
};

_f01‍.d(userController);
